benchmark: False
max_epochs: 201
accelerator: gpu
# accelerator: cpu
devices: [0]

log_every_n_steps: 1
deterministic: False
detect_anomaly: False
enable_progress_bar: True

num_sanity_val_steps: 0  # turn off sanity check

