_target_: framework.model.losses.compute_vqvae_prior.ComputeLosses

## Loss terms
# Quantization loss
lmd_quant: 1.5
quant: ${.lmd_quant}

# Reconstruction losses
lmd_exp_recons: 0.5
recons_exp: ${.lmd_exp_recons}
recons_exp_func: ${model.func_recons}

lmd_jaw_recons: 0.1
recons_jaw: ${.lmd_jaw_recons}
recons_jaw_func: ${model.func_recons}




