_target_: diffusers.DPMSolverMultistepScheduler

#num_inference_timesteps: 100
#eta: 0.0

# params:
#num_train_timesteps: 1000
#beta_start: 0.00085
#beta_end: 0.012
#beta_schedule: 'scaled_linear' # Optional: ['linear', 'scaled_linear', 'squaredcos_cap_v2']
#variance_type: 'fixed_small'

prediction_type: 'sample'


