_target_: diffusers.DDIMScheduler

#num_inference_timesteps: 100
#eta: 0.0

# params:
num_train_timesteps: 1000
beta_schedule: 'squaredcos_cap_v2' # Optional: ['linear', 'scaled_linear', 'squaredcos_cap_v2']
clip_sample: false # clip sample to -1~1
# prediction_type: 'sample'
# below are for ddim
set_alpha_to_one: false
steps_offset: 1

